# Homework: Introduction to Python

## Problem 1: Containers and Functions

**(a)** Write a function called `unique_sorted` that takes a list of integers and returns a **new** list containing the unique values in ascending order. For example, `unique_sorted([3, 1, 2, 3, 2])` should return `[1, 2, 3]`.

In [ ]:
def unique_sorted(values):
    return sorted(set(values))

In [ ]:
unique_sorted([3,1,2,3,2])

[1, 2, 3]

**(b)** Write a function called `count_words` that takes a list of strings and returns a dictionary mapping each word (lowercased) to its count. For example, `count_words(["Apple", "banana", "apple", "BANANA"])` should return `{'apple': 2, 'banana': 2}`.

In [ ]:
def count_words(words):
    counts = {}
    for w in words:
        w = w.lower()
        counts[w] = counts.get(w, 0) + 1
    return counts

In [ ]:
count_words(["Apple", "banana", "apple", "BANANA"])

{'apple': 2, 'banana': 2}

**(c)** You are given a list of `(name, score)` tuples. Write a function called `average_scores` that returns a dictionary mapping each name to their average score. If a name appears multiple times, you should average all of their scores. For example, `average_scores([("Ada", 90), ("Bob", 80), ("Ada", 100)])` should return `{'Ada': 95.0, 'Bob': 80.0}`.

In [ ]:
def average_scores(records):
    scores = {}
    for name, score in records:
        if name not in scores:
            scores[name] = []
        scores[name].append(score)
    for name in scores:
        scores[name] = sum(scores[name]) / len(scores[name])
    return scores

In [ ]:
average_scores([("Ada", 90), ("Bob", 80), ("Ada", 100)])

{'Ada': 95.0, 'Bob': 80.0}

## Problem 2: Writing Functions with Comprehensions

**(a)** Write a function called `filter_by_threshold` that takes a list of numbers and a threshold value, and returns a new list containing only the numbers greater than the threshold. Use a list comprehension. For example, `filter_by_threshold([1, 5, 3, 8, 2], 3)` should return `[5, 8]`.

In [ ]:
def filter_by_threshold(numbers, threshold):
    return [num for num in numbers if num > threshold]

In [ ]:
filter_by_threshold([1, 5, 3, 8, 2], 3)

[5, 8]

**(b)** Write a function called `word_lengths` that takes a list of strings and returns a dictionary mapping each unique word to its length. Use a dictionary comprehension. For example, `word_lengths(["hello", "world", "hi"])` should return `{'hello': 5, 'world': 5, 'hi': 2}`.

In [ ]:
def word_lengths(words):
    return {word: len(word) for word in words}

In [ ]:
word_lengths(["hello", "world", "hi"])

{'hello': 5, 'world': 5, 'hi': 2}

**(c)** Write a function called `common_elements` that takes two lists and returns a set of elements that appear in both lists. Use a set comprehension. For example, `common_elements([1, 2, 3, 4], [3, 4, 5, 6])` should return `{3, 4}`.

In [ ]:
def common_elements(list1, list2):
    return {element for element in list1 if element in list2}

In [ ]:
common_elements([1, 2, 3, 4], [3, 4, 5, 6])

{3, 4}

## Problem 3: NumPy Array Operations

**(a)** Given the following 2D array, write NumPy code to:
1. Extract the second row as a 1D array
2. Extract the last column as a 2D column vector (shape should be `(4, 1)`)
3. Extract the 2x2 subarray from the bottom-right corner

In [ ]:
import numpy as np

data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

In [ ]:
print(data[1,:])  # second row
print(data[:,-1].reshape(-1,1))  # last col as 2D vec
print(data[-2:,-2:])  # 2x2 subarray from bottom-right corner

[5 6 7 8]
[[ 4]
 [ 8]
 [12]
 [16]]
[[11 12]
 [15 16]]


**(b)** Without using loops, write NumPy code to:
1. Create a 5x5 array where each element is the sum of its row and column indices (i.e., element at position `[i, j]` should equal `i + j`)
2. Normalize each row of a matrix so that each row sums to 1 (use broadcasting)

In [ ]:
rows = np.arange(5).reshape(-1, 1)
cols = np.arange(5)
print(rows.shape, cols.shape)
array_sum_indices = rows + cols  # use broadcast
print(array_sum_indices)

(5, 1) (5,)
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [ ]:
# Given matrix for part 2
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], dtype=float)

row_sums = matrix.sum(axis=1, keepdims=True) # dim is (3,1)
normalized_matrix = matrix / row_sums
print(normalized_matrix)

[[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]
 [0.29166667 0.33333333 0.375     ]]


**(c)** Explain the difference between the following two indexing operations. What are the shapes of `a` and `b`? Which one creates a view and which creates a copy?

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = arr[0:1, :]  # 2d array, slicing creates a /view/
b = arr[[0], :]  # 2d array, advanced indexing creats a /copy/

print(f"Shape of a is {a.shape}")
print(f"Shape of b is {b.shape}")

c = arr[0,:]  # 1d array, basic indexing creates a /view/
print(f"Shape of c is {c.shape}")

Shape of a is (1, 3)
Shape of b is (1, 3)
Shape of c is (3,)


## Problem 4: Improving Inefficient Code

The following code computes pairwise distances between points but is inefficient. Rewrite it using NumPy broadcasting to eliminate the nested loops. Your solution should produce the same result as the original code.

In [ ]:
import numpy as np

def pairwise_distances_slow(points):
    """Compute pairwise Euclidean distances between points.

    Parameters
    ----------
    points : np.ndarray
        Array of shape (n, d) where n is number of points and d is dimensions.

    Returns
    -------
    np.ndarray
        Array of shape (n, n) containing pairwise distances.
    """
    n = points.shape[0]
    distances = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            diff = points[i] - points[j]
            distances[i, j] = np.sqrt(np.sum(diff ** 2))
    return distances

In [ ]:
import numpy as np

def pairwise_distances_broadcast(points):
    """Compute pairwise Euclidean distances between points using broadcasting.

    Parameters
    ----------
    points : np.ndarray
        Array of shape (n, d) where n is number of points and d is dimensions.

    Returns
    -------
    np.ndarray
        Array of shape (n, n) containing pairwise distances.
    """
    diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]  # Expand dimensions to enable broadcasting: (n, 1, d) - (1, n, d) -> (n, n, d)
    # Sum of squared differences along the last axis (dimension d)
    distances = np.sqrt(np.sum(diff ** 2, axis=2))
    return distances

In [ ]:
# Test with an example
points_example = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])

print("Original slow function output:")
slow_distances = pairwise_distances_slow(points_example)
print(slow_distances)

print("\nBroadcasted function output:")
fast_distances = pairwise_distances_broadcast(points_example)
print(fast_distances)


Original slow function output:
[[0.         1.         1.         1.41421356]
 [1.         0.         1.41421356 1.        ]
 [1.         1.41421356 0.         1.        ]
 [1.41421356 1.         1.         0.        ]]

Broadcasted function output:
[[0.         1.         1.         1.41421356]
 [1.         0.         1.41421356 1.        ]
 [1.         1.41421356 0.         1.        ]
 [1.41421356 1.         1.         0.        ]]


## Problem 5: The View Trap

A colleague wrote the following function to standardize columns of a matrix (subtract mean, divide by standard deviation). However, users are reporting unexpected behavior.

In [ ]:
import numpy as np

def standardize_columns(data):
    """Standardize each column to have mean 0 and std 1."""
    result = data
    for j in range(data.shape[1]):
        col = result[:, j]
        col_mean = np.mean(col)
        col_std = np.std(col)
        col = (col - col_mean) / col_std
    return result

**(a)** Explain why this function does not work as intended. What fundamental concept about NumPy arrays is being misunderstood?

(a) `(col - col_mean) / col_std` returns a new numpy array (with a new location in memory), which is assigned to `col` -- i.e., as a variable (previously a view of `result`), `col` is replaced by another object in memory as a whole.

**Caveat:** the original numpy array only changes with its view when the view is modified *in-place*. NumPy arithmetic operations usually return new arrays, rather than modifying existing arrays in-place

**(b)** A user runs the following code and is surprised by the output. Explain what happens and why.

In [ ]:
original = np.array([[1.0, 2.0], [3.0, 4.0]])
normalized = standardize_columns(original)
print("Original:", original)
print("Normalized:", normalized)
print("Are they the same object?", original is normalized)

Original: [[1. 2.]
 [3. 4.]]
Normalized: [[1. 2.]
 [3. 4.]]
Are they the same object? True


Inside `standardize_columns`, `result` is a view of `data` and is not modified (see explanation in (a)), so the return value is the unmodifed `data` itself (thus the memory location doesn't change).

**(c)** Rewrite the function correctly. Your solution should actually standardize the columns, not modify the input array, and use vectorized operations instead of explicit loops where possible.

**(d)** Write a simple test that verifies your corrected function works properly. The test should check that the output columns have approximately mean 0 and standard deviation 1.

In [ ]:
import numpy as np

def standardize_columns_corrected(data):
    """Standardize each column to have mean 0 and std 1."""
    result = data.copy()  # (n,d)
    col_means = np.mean(data, axis = 0)  # (d,)
    col_stds = np.std(data, axis = 0)  # (d,)
    result = (result - col_means) / col_stds
    return result

In [ ]:
original = np.array([[1.0, 2.0], [3.0, 4.0]])
# original = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
normalized = standardize_columns_corrected(original)
print("Original:", original)
print("Normalized:", normalized)
print("Are they the same object?", original is normalized)

print("col means:", np.mean(normalized, axis = 0))
print("col stds:", np.std(normalized, axis = 0))

Original: [[1. 2.]
 [3. 4.]]
Normalized: [[-1. -1.]
 [ 1.  1.]]
Are they the same object? False
col means: [0. 0.]
col stds: [1. 1.]
